version: "3.7"

services:
  text-classification:
    container_name: text-classification
    depends_on:
      - redis
      - db
    build: 
      context: .
      dockerfile: ./Dockerfile
      target: dev
      args: 
        DATABASE__CREATE: "True"
    networks:
      - shared
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    command: ["python", "-m", "app"]

  redis:
    container_name: redis
    image: redis:4.0.11-alpine
    networks:
      - shared
    restart: always
    init: true
    stop_grace_period: 30s

  celery:
    depends_on:
      - redis
    container_name: celery-worker
    volumes:
      - ./:/app
    build: 
      context: .
      dockerfile: ./Dockerfile
      target: dev
      args: 
        DATABASE__CREATE: "False"
    command: celery -A celery_worker.celery worker -l INFO
    networks:
      - shared

  db:
    image: postgres
    container_name: postgres_development
    environment: 
      POSTGRES_USER: "postgres_development"
      POSTGRES_PASSWORD: "dbs_development"
      POSTGRES_DB: "text_classification_development"
    ports:
      - 5432:5432
    restart: always
    init: true
    networks:
      - shared

networks:
  shared:
    name: shared-network
