version: "3.7"

services:
  text-classification:
    container_name: text-classification
    depends_on: 
      - redis
      - db
    build: 
      context: .
      dockerfile: ./Dockerfile
      target: prod
    networks:
      - shared
    volumes:
      - ./:/app
    command: [ "uwsgi", "app.ini" ]

  redis:
    container_name: redis
    image: redis:4.0.11-alpine
    networks:
      - shared
    restart: always
    init: true
    stop_grace_period: 30s

  celery:
    depends_on: 
      - redis
    container_name: celery-worker
    volumes:
      - ./:/app
    build: 
      context: .
      dockerfile: ./Dockerfile
      target: prod
    command: celery -A celery_worker.celery worker -l INFO
    networks: 
      - shared

  db:
    image: postgres
    container_name: postgres_production
    environment: 
      POSTGRES_USER: "postgres_production"
      POSTGRES_PASSWORD: "dbs_production"
      POSTGRES_DB: "text_classification_production"
    restart: always
    init: true
    networks:
      - shared

  nginx:
    build: ./nginx
    container_name: nginx
    depends_on: 
      - text-classification
    networks: 
      - shared
    restart: always
    ports:
      - "80:80"


networks:
  shared:
    name: shared-network