version: "3.7"

services:
  text-classification:
    container_name: text-classification
    depends_on: 
      - redis
    image: adamstuller/text-classification-flask:1.1
    networks:
      - shared
    volumes:
      - ./:/app
    environment:
      FLASK_ENV: "development"
      REDIS_URL: 'redis'
    ports:
      - "5000:5000"
    command: ["python", "-m", "app"]

  redis:
    container_name: redis
    image: redis:4.0.11-alpine
    networks:
      - shared
    ports:  
      - "6379:6379"
    restart: always
    init: true
    stop_grace_period: 30s

  celery:
    depends_on: 
      - redis
    container_name: celery-worker
    environment:
      REDIS_URL: 'redis'
      FLASK_ENV: "development"
    volumes:
      - ./:/app
    image: adamstuller/text-classification-flask:1.1
    command: celery -A celery_worker.celery worker -l INFO
    networks: 
      - shared

networks:
  shared:
    name: shared-network