DATASET_ARG = 'dataset'
PIPELINE_ARG = 'pipeline'
DEFAULT_DATASET = 'updated_banks'

# Column names 
POSTED_BY_COLUMN_NAME = 'posted_by'
CLASS_COLUMN_NAME = 'tag'
SENTENCE_COLUMN_NAME = 'sentence'
UPDATED_SENTENCE_COLUMN_NAME = 'updated_sentence'
SENTIMENT_PERCENTAGE_COLUMN_NAME = 'sentiment_percentage'
POST_ID_COLUMN_NAME = 'post_id'
PARENT_CLASS_COLUMN_NAME = 'parent_tag'
LIKES_COLUMN_NAME = 'likes'

COLUMN_NAMES = [CLASS_COLUMN_NAME, SENTENCE_COLUMN_NAME, LIKES_COLUMN_NAME,
                SENTIMENT_PERCENTAGE_COLUMN_NAME, POST_ID_COLUMN_NAME, POSTED_BY_COLUMN_NAME, PARENT_CLASS_COLUMN_NAME]
UPDATED_COLUMN_NAMES = [CLASS_COLUMN_NAME, LIKES_COLUMN_NAME, SENTIMENT_PERCENTAGE_COLUMN_NAME,
                        POST_ID_COLUMN_NAME, POSTED_BY_COLUMN_NAME, PARENT_CLASS_COLUMN_NAME, UPDATED_SENTENCE_COLUMN_NAME]

